services:
  - type: web
    name: financial-dashboard-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://financial-dashboard-2-black.vercel.app
    autoDeploy: true